#ifndef __RECOMP_LIBC__
#define __RECOMP_LIBC__
#include <modding.h>

#ifndef ENABLE_UNIMPLEMENTED_LIBC_APIS
#define DISABLE_UNIMPLEMENTED_LIBC_APIS 
#endif

#define RECOMP_LIBC_ASSERT_MOD_ID "recomp_libc_combined"
#define RECOMP_LIBC_CTYPE_MOD_ID "recomp_libc_combined"
#define RECOMP_LIBC_PRINTF_MOD_ID "recomp_libc_combined"
#define RECOMP_LIBC_STDLIB_MOD_ID "recomp_libc_combined"
#define RECOMP_LIBC_STRING_MOD_ID "recomp_libc_combined"
#define RECOMP_LIBC_SUPPORT_MOD_ID "recomp_libc_combined"

#ifdef RECOMP_IS_BUILDING_combined
#define RECOMP_ASSERT_DECLARATION(func_dec) func_dec
#define RECOMP_ASSERT_DEFINITION RECOMP_EXPORT
#define RECOMP_CTYPE_DECLARATION(func_dec) func_dec
#define RECOMP_CTYPE_DEFINITION RECOMP_EXPORT
#define RECOMP_PRINTF_DECLARATION(func_dec) func_dec
#define RECOMP_PRINTF_DEFINITION RECOMP_EXPORT
#define RECOMP_STDLIB_DECLARATION(func_dec) func_dec
#define RECOMP_STDLIB_DEFINITION RECOMP_EXPORT
#define RECOMP_STRING_DECLARATION(func_dec) func_dec
#define RECOMP_STRING_DEFINITION RECOMP_EXPORT
#define RECOMP_SUPPORT_DECLARATION(func_dec) func_dec
#define RECOMP_SUPPORT_DEFINITION RECOMP_EXPORT
#else
#define RECOMP_ASSERT_DECLARATION(func_dec) RECOMP_IMPORT(RECOMP_LIBC_ASSERT_MOD_ID, func_dec);
#define RECOMP_ASSERT_DEFINITION
#define RECOMP_CTYPE_DECLARATION(func_dec) RECOMP_IMPORT(RECOMP_LIBC_CTYPE_MOD_ID, func_dec);
#define RECOMP_CTYPE_DEFINITION
#define RECOMP_PRINTF_DECLARATION(func_dec) RECOMP_IMPORT(RECOMP_LIBC_PRINTF_MOD_ID, func_dec);
#define RECOMP_PRINTF_DEFINITION
#define RECOMP_STDLIB_DECLARATION(func_dec) RECOMP_IMPORT(RECOMP_LIBC_STDLIB_MOD_ID, func_dec);
#define RECOMP_STDLIB_DEFINITION
#define RECOMP_STRING_DECLARATION(func_dec) RECOMP_IMPORT(RECOMP_LIBC_STRING_MOD_ID, func_dec);
#define RECOMP_STRING_DEFINITION
#define RECOMP_SUPPORT_DECLARATION(func_dec) RECOMP_IMPORT(RECOMP_LIBC_SUPPORT_MOD_ID, func_dec);
#define RECOMP_SUPPORT_DEFINITION
#endif


#endif // __RECOMP_LIBC__
